In [1]:
import numpy as np


In [2]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr2d = arr.reshape(3,3)
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr2d.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr2d.flatten("F") # F fortan

array([1, 4, 7, 2, 5, 8, 3, 6, 9])

In [7]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
arr2d.flatten("F")

array([1, 4, 7, 2, 5, 8, 3, 6, 9])

In [9]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
arr2d.flatten("c")

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.linspace(1,3,7)

array([1.        , 1.33333333, 1.66666667, 2.        , 2.33333333,
       2.66666667, 3.        ])

## MATHEMATICAL METHOD

In [12]:
arr1 = np.arange(1,10).reshape((3,3))
arr2 = np.arange(3,12).reshape((3,3))
arr1,arr2

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]))

In [13]:
np.add(arr2,arr1)

array([[ 4,  6,  8],
       [10, 12, 14],
       [16, 18, 20]])

In [14]:
arr2 +arr1

array([[ 4,  6,  8],
       [10, 12, 14],
       [16, 18, 20]])

In [15]:
np.subtract(arr2,arr1)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [16]:
arr2 - arr1

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [17]:
np.multiply(arr2,arr1)

array([[ 3,  8, 15],
       [24, 35, 48],
       [63, 80, 99]])

In [18]:
arr1 * arr2

array([[ 3,  8, 15],
       [24, 35, 48],
       [63, 80, 99]])

In [19]:
np.divide(arr2,arr1)

array([[3.        , 2.        , 1.66666667],
       [1.5       , 1.4       , 1.33333333],
       [1.28571429, 1.25      , 1.22222222]])

In [20]:
arr2 / arr1

array([[3.        , 2.        , 1.66666667],
       [1.5       , 1.4       , 1.33333333],
       [1.28571429, 1.25      , 1.22222222]])

In [21]:
arr3 = np.array([10,20,30])
arr3

array([10, 20, 30])

In [22]:
arr1 + arr3

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39]])

In [23]:
arr1,arr3

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([10, 20, 30]))

In [24]:
arr1,arr2

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]))

In [25]:
np.dot(arr1,arr2)

array([[ 42,  48,  54],
       [ 96, 111, 126],
       [150, 174, 198]])

In [26]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [27]:
np.log(arr1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [28]:
np.log10(arr1)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])

# CONCATNATION

In [29]:
arr1,arr2

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]))

In [30]:
np.concatenate([arr1,arr2])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [31]:
np.concatenate([arr1,arr2],axis=1)

array([[ 1,  2,  3,  3,  4,  5],
       [ 4,  5,  6,  6,  7,  8],
       [ 7,  8,  9,  9, 10, 11]])

## SPLITTING

In [32]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
np.split(arr1,3,axis=1)

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

In [34]:
np.split(arr1 ,3)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]