In [1]:
import numpy as np

In [2]:
np.random.random()

0.5455404707814532

In [5]:
team1 = np.random.randint(0,36,20)
team1

array([ 7, 28, 25,  2, 17, 22, 15, 31, 21, 12, 27,  0,  7,  7,  4, 31, 32,
       32,  9, 21], dtype=int32)

In [7]:
np.random.randint(0,36,(4,5))

array([[22, 14,  1, 23, 31],
       [10, 28,  2, 20,  7],
       [25, 18, 15,  3,  9],
       [21, 22, 22, 10, 20]], dtype=int32)

In [8]:
np.random.seed(10)
np.random.randint(0,100,1)

array([9], dtype=int32)

In [9]:
np.random.rand()

0.29876115188562824

In [10]:
np.random.randn(10)

array([-2.93119247, -0.27828276,  0.29986131,  1.19449472, -0.90561048,
       -0.89808938,  0.45187984, -0.85947418, -0.53479453,  1.03287114])

In [13]:
dice = np.arange(1,7)

In [14]:
np.random.choice(dice,1)

array([1])

In [15]:
dice

array([1, 2, 3, 4, 5, 6])

In [17]:
np.random.permutation(dice)

array([6, 1, 2, 5, 3, 4])

In [18]:
np.sin(np.radians(30))

np.float64(0.49999999999999994)